[[redirects]]
  from = "/api/*"
  to = "http://soteriasoftware-env.eba-mvxhuyra.sa-east-1.elasticbeanstalk.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
